name: john-the-ripper
version: 1.8.0-J1-f22de0a
confinement: devmode
summary: John the Ripper "Jumbo" password cracker
description: John the Ripper is a fast password cracker, currently available for many flavors of Unix, Windows, DOS, BeOS, and OpenVMS. Its primary purpose is to detect weak Unix passwords. Besides several crypt(3) password hash types most commonly found on various Unix systems, supported out of the box are Windows LM hashes, plus lots of other hashes and ciphers. This package supports OpenCL.

apps:
  john-the-ripper:
    command: run/john

  opencl:
    command: opencl/john
    plugs: [opencl]

parts:
  john-the-ripper:
    plugin: autotools
    source: git://github.com/magnumripper/JohnTheRipper
    source-type: git
    source-subdir: ./src

    build-packages: 
      - build-essential 
      - libssl-dev 
      - git 
      - libgmp-dev 
      - libpcap-dev
      - libbz2-dev
      - opencl-headers

  opencl:
    plugin: autotools
    source: git://github.com/magnumripper/JohnTheRipper
    source-type: git
    source-subdir: ./src

  libs:
    plugin: nil
    stage-packages:
      - openssl 
      - libgomp1
      - libgmp10
      - libbz2-1.0
      - ocl-icd-libopencl1

  transfer:
    plugin: copy
    after: [john-the-ripper, opencl]
    files:
      ../../john-the-ripper/build/run/*: run/
      ../../opencl/build/run/*: opencl/
      ../../opencl/build/doc/*: doc/
      ../../opencl/build/README: README
      ../../opencl/build/README.md: README.md
      ../../opencl/build/README-jumbo: README-jumbo
      ../install/opencl/john.bash_completion: etc/bash_completion.d/

