name: john-the-ripper
version: edge
confinement: strict
summary: John the Ripper "Jumbo" password cracker
description: John the Ripper is a fast password cracker, currently available for many flavors of Unix, Windows, DOS, BeOS, and OpenVMS. Its primary purpose is to detect weak Unix passwords. Besides several crypt(3) password hash types most commonly found on various Unix systems, supported out of the box are Windows LM hashes, plus lots of other hashes and ciphers.

apps:
  john-the-ripper:
    command: run/john
  opencl:
    command: run/john-opencl
  dmg2john:
    command: run/dmg2john 
  hccap2john:
    command: run/hccap2john    
  pfx2john:
    command: run/pfx2john    
  racf2john:
    command: run/racf2john  
  vncpcap2john:
    command: run/vncpcap2john  
  zip2john:
    command: run/zip2john
  gpg2john:
    command: run/gpg2john  
  keepass2john:
    command: run/keepass2john  
  putty2john:
    command: run/putty2john  
  rar2john:
    command: run/rar2john   
  uaf2john:
    command: run/uaf2john  
  wpapcap2john:
    command: run/wpapcap2john

parts:
  john-the-ripper:
    plugin: make
    after: [regex]
    source: .

    build-packages: 
      - build-essential 
      - libssl-dev 
      - libgmp-dev 
      - libpcap-dev
      - libbz2-dev
      - opencl-headers
      - git
      - wget
      - patch

    organize:
      ../build/run/: run/
      ../build/doc/: doc/
      ../build/README: README
      ../build/README.md: README.md
      ../build/README-jumbo: README-jumbo
      ../build/john-the-ripper.opencl: john-the-ripper.opencl

  regex:
    plugin: cmake
    source: https://github.com/teeshop/rexgen.git
    source-type: git
    source-subdir: ./src
    #source-tag: release #159baaf6ad123dcd5b02672b424049527677aef3

    build-packages:
      - build-essential
      - flex
      - bison
      - libicu-dev

  libs:
    plugin: nil

    stage-packages:
      - openssl 
      - libgomp1
      - libgmp10
      - libpcap0.8
      - libbz2-1.0
      - ocl-icd-libopencl1

    filesets:
      extras:
        - -usr/local/man
        - -usr/share/
    snap:
      - $extras
    stage:
      - $extras

  transfer:
    plugin: dump
    after: [john-the-ripper]
    source: https://github.com/magnumripper/JohnTheRipper/archive/bleeding-jumbo.zip

    snap:
      - etc/
    stage:
      - etc/

    organize:
      JohnTheRipper-bleeding-jumbo/run/john.bash_completion: etc/bash_completion/john.bash_completion
      JohnTheRipper-bleeding-jumbo/run/john.zsh_completion: etc/bash_completion/john.zsh_completion

