name: john-the-ripper
version: 1.8.0-J1-f22de0a
confinement: strict
summary: John the Ripper "Jumbo" password cracker
description: John the Ripper is a fast password cracker, currently available for many flavors of Unix, Windows, DOS, BeOS, and OpenVMS. Its primary purpose is to detect weak Unix passwords. Besides several crypt(3) password hash types most commonly found on various Unix systems, supported out of the box are Windows LM hashes, plus lots of other hashes and ciphers.

apps:
  john-the-ripper:
    command: run/john

parts:
  john-the-ripper:
    plugin: autotools
    source: https://github.com/claudioandre/JohnTheRipper.git
    source-branch: snap_package
    source-type: git
    source-subdir: ./src

    build-packages: 
      - build-essential 
      - libssl-dev 
      - git 
      - libgmp-dev 
      - libpcap-dev
      - libbz2-dev
      - opencl-headers

  libs:
    plugin: nil
    stage-packages:
      - openssl 
      - libgomp1
      - libgmp10
      - libbz2-1.0
      - ocl-icd-libopencl1

  transfer:
    plugin: copy
    after: [john-the-ripper, libs]
    files:
      ../../john-the-ripper/build/run/*: run/
      ../../john-the-ripper/build/doc/*: doc/
      ../../john-the-ripper/build/README: README
      ../../john-the-ripper/build/README.md: README.md
      ../../john-the-ripper/build/README-jumbo: README-jumbo
      ../../john-the-ripper/build/run/john.bash_completion: bash_completion/john.bash_completion

