language: c
dist: trusty

matrix:
  include:
  - env: DISTRO=ubuntu IMAGE=ubuntu:xenial

#build for other distros/images using:
#env: DISTRO=ubuntu IMAGE=ubuntu:16.10

before_install:
  - docker pull "$IMAGE"
  - git clone git://git.sv.gnu.org/autoconf-archive.git autoconf
  - git clone https://github.com/GNOME/gjs.git
  - git clone https://github.com/GNOME/glib.git
  - git clone https://github.com/GNOME/gobject-introspection.git

script:
  - mkdir -p gjs/m4
  - cp autoconf/m4/ax_*.m4 gjs/m4/
  - cp gobject-introspection/m4/*.m4 gjs/m4/
  - docker run -v $(pwd):/cwd -v $(pwd)/check.sh:/check.sh -e "DISTRO=$DISTRO" "$IMAGE" bash -e /check.sh


