name: peazip
version: 6.3.0
confinement: strict
grade: stable
summary: Free file archiver and encryption software
description: >
             PeaZip is a free file archiver utility, based on Open Source technologies of 7-Zip, p7zip, FreeArc, PAQ, and PEA projects. It deploys a powerful and complete file manager, featuring a wide set of data security functions: strong encryption, encrypted password manager, secure delete, and file hashing.

apps:
  peazip:
    command: desktop-launch $SNAP/bin/wrapper
    plugs: [home, x11, unity7, gsettings]

parts:
  peazip:
    plugin: dump
    after: [desktop-gtk2]
    source: ./peazip_portable-6.3.0.LINUX.GTK2

    stage-packages:
      - libgail-common:i386
      - libatk-adaptor:i386
      - libcanberra-gtk-module:i386
      - overlay-scrollbar
      - unity-gtk-module-common
      - xdg-utils

      - libc6:i386
      - libglib2.0-0:i386
      - libgmp10:i386
      - libcurl3:i386
      - libncurses5:i386
      - libstdc++6:i386
      - libatk1.0-0:i386
      - libcairo2:i386
      - libgdk-pixbuf2.0-0:i386
      - libgtk2.0-0:i386
      - libpango1.0-0:i386
      - libx11-6:i386

    stage:
      - -readme_Linux1.txt
      - -FreeDesktop_integration

    organize:
      res/*: bin/res
      wrapper: bin/wrapper
      peazip: bin/peazip
      peazip_help.pdf: bin/peazip_help.pdf

    # cp wrapper peazip_portable-6.3.0.LINUX.GTK2
