name: doctl
version: 1.4.0
confinement: strict
summary: DigitalOcean's command line interface for the API
description: doctl is a command line interface for the DigitalOcean API. Use "doctl [command] --help" for more information about a command.

apps:
  doctl:
    command: doctl
    plugs: [network, network-bind]

parts:
  transfer:
    plugin: dump
    source: https://github.com/digitalocean/doctl/releases/download/v1.4.0/doctl-1.4.0-linux-amd64.tar.gz

    snap:
      - doctl
    stage:
      - doctl

