name: anatine
version: edge
confinement: classic
summary: Pristine Twitter app
description: This app is based the awesome Mobile Twitter site, but modifies a lot of things and makes it more usable on the desktop.

apps:
  anatine:
    command: bin/Anatine
#    plugs: [home, x11, unity7, gsettings, opengl, pulseaudio, alsa, network, network-bind, process-control, browser-support]

parts:
  anatine:
    plugin: make
    after: [prepare]
#   after: [desktop-gtk2, indicator-gtk2, prepare]
    source: .

    build-packages:
      - git
      - npm
      - nodejs-legacy
      - wget
      - sed
      - gnome-common
      - gtk-doc-tools

#   stage-packages:
#     - libxtst6
#     - libxss1
#     - libdbusmenu-gtk4
#     - libgconf2-4
#     - libnss3
#     - overlay-scrollbar
#     - libgail-common
#     - libatk-adaptor
#     - unity-gtk-module-common
#     - libcanberra-gtk-module

    stage:
#     - -usr/sbin/update-icon-caches
      - -bin/static

#  desktop-gtk2:
#    stage: [ -./**/libappindicator*.so.* ]

#  snapd-xdg-open:
#    plugin: dump
#    source: https://github.com/ubuntu-core/snapd-xdg-open.git

#    prime:
#      - bin/xdg-open

#    organize:
#      data/xdg-open: bin/xdg-open

#  wrapper:
#    plugin: dump
#    source: alsa/

#    stage-packages:
#      - alsa-utils

  prepare:
    plugin: nil
    source: .
    build: |
      ./build.sh PREPARE

